name: Integration Testing (dev)

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup auxillary systems
        run: |
          docker run --name evatool-test-db -p 3306:3306 -e MYSQL_ROOT_PASSWORD=admin -e MYSQL_DATABASE=evatooldb -d mysql:8.0.24
          git clone --branch dev https://github.com/EVATool/evatool-backend
          docker run --name evatool-test-auth -p 8081:8080 -v ${PWD}/evatool-backend/src/main/resources/auth/keycloak:/opt/jboss/keycloak/imports -e KEYCLOAK_USER=admin -e KEYCLOAK_PASSWORD=admin -e KEYCLOAK_IMPORT=/opt/jboss/keycloak/imports/evatool-realm.json -d quay.io/keycloak/keycloak:13.0.0
          sleep 15

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build and start backend
        run: |
          cd evatool-backend
          mvn clean install -P integration -Dmaven.test.skip=true --file pom.xml
          java -jar ./target/evatool-0.0.1-SNAPSHOT.jar &
          sleep 15

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Integration Test
        run: |
          npm ci
          npm run test:integration
