name: Integration Testing (dev)

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup auxillary systems
        run: |
          docker run --name evatool-test-db -p 3306:3306 -e MYSQL_ROOT_PASSWORD=admin -e MYSQL_DATABASE=evatooldb -d mysql:8.0.24
          # TODO Make dir for realm import and download json realm file.
          docker run --name evatool-test-auth -p 8081:8080 -v ${PWD}/src/main/resources/auth/keycloak:/opt/jboss/keycloak/imports -e KEYCLOAK_USER=admin -e KEYCLOAK_PASSWORD=admin -e KEYCLOAK_IMPORT=/opt/jboss/keycloak/imports/evatool-realm.json -d quay.io/keycloak/keycloak:13.0.0
          mvn flyway:migrate
          sleep 15
          # TODO start backend.

      - name: Integration Test
        run: |
          npm ci
          npm run test:integration
