name: CI Deployment (main)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    #- run: npm run test:prod
    - run: npm run build:prod

#    - name: Transfer docker folder to remote server
#      uses: garygrossgarten/github-action-scp@release
#      with:
#        local: docker
#        remote: evatool/frontend/docker
#        host: ${{ secrets.HOST }}
#        username: ${{ secrets.USER }}
#        privatekey: ${{ secrets.SSH_PRIVATE_KEY }}
#        port: ${{ secrets.PORT }}
#
#    - name: Transfer dist folder to remote server
#      uses: garygrossgarten/github-action-scp@release
#      with:
#        local: dist
#        remote: evatool/frontend/docker/dist
#        host: ${{ secrets.HOST }}
#        username: ${{ secrets.USER }}
#        privatekey: ${{ secrets.SSH_PRIVATE_KEY }}
#        port: ${{ secrets.PORT }}
#
#    - name: Run deploy script
#      uses: appleboy/ssh-action@master
#      env:
#        HOST: ${{ secrets.HOST }}
#        USERNAME: ${{ secrets.USER }}
#        KEY: ${{ secrets.SSH_PRIVATE_KEY }}
#        PORT: ${{ secrets.PORT }}
#        SCRIPT: sh evatool/frontend/docker/deploy.sh

        - name: copy file
          uses: canastro/copy-file-action@master
          with:
            source: "dist"
            target: "docker/dist"

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v1
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Build and push
          id: docker_build
          uses: docker/build-push-action@v2
          with:
            context: ./docker
            push: true
            tags: evatool/evatool-frontend:latest
        - name: Image digest
          run: echo ${{ steps.docker_build.outputs.digest }}
