name: CI Deployment (main)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build:prod

    - name: Transfer docker folder to remote server
      uses: garygrossgarten/github-action-scp@release
      with:
        local: docker/deploy.sh
        remote: evatool/frontend/docker/deploy.sh
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        privatekey: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}

    - name: Transfer dist folder to remote server
      uses: garygrossgarten/github-action-scp@release
      with:
        local: dist
        remote: evatool/frontend/dist
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        privatekey: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}

    - name: Run deploy script
      uses: appleboy/ssh-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USER }}
        KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        PORT: ${{ secrets.PORT }}
        SCRIPT: sh evatool/frontend/docker/deploy.sh